package my.suveng.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends JbootModel<M> implements IBean {

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.Integer getId() {
        return getInt("id");
    }

    public void setUsername(java.lang.String username) {
        set("username", username);
    }

    public java.lang.String getUsername() {
        return getStr("username");
    }

    public void setPassword(java.lang.String password) {
        set("password", password);
    }

    public java.lang.String getPassword() {
        return getStr("password");
    }

}
